// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGLMqDtFMlcQ9iK0jKDJe4ScXT1iEbfrY',
    appId: '1:912059002594:web:46e8bec9577a3f02eaf8bb',
    messagingSenderId: '912059002594',
    projectId: 'store-3dd2b',
    authDomain: 'store-3dd2b.firebaseapp.com',
    storageBucket: 'store-3dd2b.appspot.com',
    measurementId: 'G-5JJJBMMLV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl8XR5w9ZZpQ3sRVitAfTMizxBi8CGRPw',
    appId: '1:912059002594:android:4becba38f4d56563eaf8bb',
    messagingSenderId: '912059002594',
    projectId: 'store-3dd2b',
    storageBucket: 'store-3dd2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcKRXYKB5dY19luVpA6d2AW_zaSxIZOHw',
    appId: '1:912059002594:ios:0ad051b8914aaee1eaf8bb',
    messagingSenderId: '912059002594',
    projectId: 'store-3dd2b',
    storageBucket: 'store-3dd2b.appspot.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcKRXYKB5dY19luVpA6d2AW_zaSxIZOHw',
    appId: '1:912059002594:ios:8fffce15eed11e40eaf8bb',
    messagingSenderId: '912059002594',
    projectId: 'store-3dd2b',
    storageBucket: 'store-3dd2b.appspot.com',
    iosBundleId: 'com.example.store.RunnerTests',
  );
}
